name       : python-imagesize
version    : 1.2.0
release    : 6
source     :
    - https://pypi.io/packages/source/i/imagesize/imagesize-1.2.0.tar.gz : b1f6b5a4eab1f73479a50fb79fcf729514a900c341d8503d62a62dbc4127a2b1
license    : MIT
component  : programming.python
summary    : Python lib for getting image size from png/jpeg/jpeg2000/gif file
description: |
    Python lib for getting image size from png/jpeg/jpeg2000/gif file
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
