name       : python-imagesize
version    : 0.7.1
release    : 3
source     :
    - https://pypi.python.org/packages/53/72/6c6f1e787d9cab2cc733cf042f125abec07209a58308831c9f292504e826/imagesize-0.7.1.tar.gz : 0ab2c62b87987e3252f89d30b7cedbec12a01af9274af9ffa48108f2c13c6062
license    : MIT
component  : programming.python
summary    : Python lib for getting image size from png/jpeg/jpeg2000/gif file
description: |
    Python lib for getting image size from png/jpeg/jpeg2000/gif file
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
