name       : python-imagesize
version    : 1.3.0
release    : 8
source     :
    - https://pypi.io/packages/source/i/imagesize/imagesize-1.3.0.tar.gz : cd1750d452385ca327479d45b64d9c7729ecf0b3969a58148298c77092261f9d
license    : MIT
component  : programming.python
summary    : Python lib for getting image size from png/jpeg/jpeg2000/gif file
description: |
    Python lib for getting image size from png/jpeg/jpeg2000/gif file
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
